### ISSUE TITLE
MVP Checklist

### ISSUE THREAD

**Issue by iProgYou** [teriley138/myTubeClone#2]
# MVP List
- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points
## Comments
- The formatting could use some work. Make sure the headers are bolded and the bullet points are indented. Makes it easier to read
- You need to do Video CRUD before you will be able to do likes/dislikes,comments, or search. So it needs to be moved around a bit
- Priority should be: Users and auth, Video CRUD and index, then comments, then likes/dislikes. Comments and likes are small, but the Video CRUD is huge.

**Comment by teriley138** [comment]
I indented the bullet points but for some reason they are now not filled in. I tried to fix it but Im not sure how. I think I fixed the priority correctly.

**Comment by iProgYou** [comment]
Reopening until full approval
